language: node_js

node_js:
  - '12'
  - '13'

addons:
  apt:
    packages:
    - libgconf-2-4

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - sudo ln /usr/local/bin/hugo /usr/local/bin/hugo-0.47.1

script: make test
