baseURL = "https://ohcoe.ctl.columbia.edu"
languageCode = "en-us"
title = "Oral Health Care in the Opioid Crisis"
googleAnalytics = "G-QNPRH4YYFB"

[menu]
  [[menu.main]]
    identifier = "domains"
    name = "Domains"
    weight = 2
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    weight = 4
