name: build-and-test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x, 13x]
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Install Hugo
        run: wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.deb
        run: sudo dpkg -i /tmp/hugo.deb
        run: sudo ln /usr/local/bin/hugo /usr/local/bin/hugo-0.47.1
      - name: Build with Makefile
        run: make test
